iversion: 0.2
env:
  variables:
    AWS_DEFAULT_REGION: $AWS_REGION
    EKS_CLUSTER_NAME: sample-eks-cluster   # we'll create this below
    ECR_REPO: $ECR_URI
phases:
  pre_build:
    commands:
      - echo Configuring kubectl
      - aws eks --region $AWS_DEFAULT_REGION update-kubeconfig --name $EKS_CLUSTER_NAME
      - IMAGE_TAG=$(cat image_tag.txt || echo "${CODEBUILD_RESOLVED_SOURCE_VERSION:0:7}")
  build:
    commands:
      - echo Replacing image placeholder in manifest
      - sed -i "s|REPLACE_IMAGE|$ECR_REPO:$IMAGE_TAG|g" k8s/deployment.yaml
      - kubectl apply -f k8s/
artifacts:
  files: []

